# Generated by Django 5.0.3 on 2026-05-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_create_signeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingapplication',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='document_type',
            field=models.CharField(choices=[('lease', 'Resident Lease Agreement'), ('emergency_contact', 'Emergency Contact Form'), ('painted_lady_acknowledgment', 'Painted Lady Acknowledgment'), ('lead_disclosure', 'Lead Disclosure'), ('asbestos_disclosure', 'Asbestos Disclosure'), ('house_rules', 'House Rules'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
